#!/usr/bin/env bash
set -euo pipefail

# Single-script build for all pipelines:
#   features_extract + categorical_classifier + messaging_classifier + multimedia_classifier
#
# Save as: ~/dpdk/arm_lib_build.sh
# Run with sudo if needed.

DPDK_SRC_ROOT=/home/ubuntu/dpdk
DPDK_INSTALL_INC=/usr/local/include
DPDK_LIB_DIR=/usr/local/lib/aarch64-linux-gnu

# -------------------------------------------------------------------
# Source files generated by pipeline codegen (expected at /tmp)
# -------------------------------------------------------------------
FEAT_SRC=/tmp/features_extract.c
CLF_SRC=/tmp/categorical_classifier.c
MSG_CLF_SRC=/tmp/messaging_classifier.c
MM_CLF_SRC=/tmp/multimedia_classifier.c

# -------------------------------------------------------------------
# Output shared objects
# -------------------------------------------------------------------
FEAT_SO=/tmp/features_extract.so
CLF_SO=/tmp/categorical_classifier.so
MSG_CLF_SO=/tmp/messaging_classifier.so
MM_CLF_SO=/tmp/multimedia_classifier.so

# -------------------------------------------------------------------
# Compiler (prefer cross-compiler)
# -------------------------------------------------------------------
CC=aarch64-linux-gnu-gcc
if ! command -v "${CC}" >/dev/null 2>&1; then
  echo "Warning: ${CC} not found; falling back to system gcc"
  CC=gcc
fi

# -------------------------------------------------------------------
# Temporary directory for object files
# -------------------------------------------------------------------
TMPDIR="$(mktemp -d /tmp/dpdk_build.XXXXXX)"
trap 'rm -rf "${TMPDIR}"' EXIT

# -------------------------------------------------------------------
# Compile & link flags
# -------------------------------------------------------------------
OBJ_FLAGS="-O3 -fPIC -Wall -Wno-deprecated-declarations -Wno-discarded-qualifiers"

INC_FLAGS="-I${DPDK_INSTALL_INC} \
           -I${DPDK_SRC_ROOT}/lib/pipeline \
           -I${DPDK_SRC_ROOT}/config"

COMMON_LINK_FLAGS="-L${DPDK_LIB_DIR} \
  -lrte_pipeline -lrte_eal -lrte_mbuf -lrte_mempool -lrte_ring \
  -lrte_ethdev -lrte_table -lrte_log -lrte_timer -lrte_hash -lrte_kvargs \
  -Wl,-z,defs -Wl,-rpath,${DPDK_LIB_DIR}"

# -------------------------------------------------------------------
# Build helper
# -------------------------------------------------------------------
build_one() {
  local SRC="$1"
  local OUT_SO="$2"
  local OBJ="${TMPDIR}/$(basename "${SRC%.*}").o"

  if [ ! -f "${SRC}" ]; then
    echo "ERROR: source not found: ${SRC}"
    echo "Run pipeline codegen first (pipeline codegen <spec> <out.c>)"
    return 2
  fi

  echo "------------------------------------------------------------"
  echo "Building: $(basename "${OUT_SO}")"
  echo "  SRC: ${SRC}"
  echo "  OBJ: ${OBJ}"
  echo "  OUT: ${OUT_SO}"
  echo "------------------------------------------------------------"

  echo "[1/2] Compiling..."
  "${CC}" ${OBJ_FLAGS} ${INC_FLAGS} -c "${SRC}" -o "${OBJ}"

  echo "[2/2] Linking..."
  "${CC}" -shared -o "${OUT_SO}" "${OBJ}" ${COMMON_LINK_FLAGS}

  echo
  file "${OUT_SO}" || true
  ls -lh "${OUT_SO}" || true
  echo "✓ Built ${OUT_SO}"
  echo
}

# -------------------------------------------------------------------
# Build all pipelines
# -------------------------------------------------------------------
echo "Starting build of all pipelines"
echo "Using tempdir: ${TMPDIR}"
echo

build_one "${FEAT_SRC}"     "${FEAT_SO}"
build_one "${CLF_SRC}"      "${CLF_SO}"
build_one "${MSG_CLF_SRC}"  "${MSG_CLF_SO}"
build_one "${MM_CLF_SRC}"   "${MM_CLF_SO}"

echo "============================================================"
echo "All builds finished successfully"
echo "============================================================"

echo
echo "Next steps:"
echo " 1) Verify all shared objects:"
echo "      ls -lh \\"
echo "        ${FEAT_SO} \\"
echo "        ${CLF_SO} \\"
echo "        ${MSG_CLF_SO} \\"
echo "        ${MM_CLF_SO}"
echo
echo " 2) Start pipeline (example):"
echo "      sudo examples/pipeline/build/pipeline -c 0x1FF -- -s /home/ubuntu/etc_pipeline_build.cli"
echo
echo "If pipeline reports:"
echo "  'Pipeline build failed (-5)'"
echo "then the build is fine, but the runtime rejected one of the classifier pipelines."
echo "In that case, paste:"
echo "  - messaging_classifier.spec"
echo "  - multimedia_classifier.spec"
echo "  - pipeline*.io"
echo "and I will inspect them."